// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	ExternalTx
	ExternalReceipt
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExternalTx struct {
	HiData string `protobuf:"bytes,1,opt,name=HiData" json:"HiData,omitempty"`
}

func (m *ExternalTx) Reset()                    { *m = ExternalTx{} }
func (m *ExternalTx) String() string            { return proto.CompactTextString(m) }
func (*ExternalTx) ProtoMessage()               {}
func (*ExternalTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExternalTx) GetHiData() string {
	if m != nil {
		return m.HiData
	}
	return ""
}

type ExternalReceipt struct {
	BlockHeight int64  `protobuf:"varint,1,opt,name=BlockHeight" json:"BlockHeight,omitempty"`
	AccountID   []byte `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	TxHash      []byte `protobuf:"bytes,3,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Log         string `protobuf:"bytes,4,opt,name=Log" json:"Log,omitempty"`
}

func (m *ExternalReceipt) Reset()                    { *m = ExternalReceipt{} }
func (m *ExternalReceipt) String() string            { return proto.CompactTextString(m) }
func (*ExternalReceipt) ProtoMessage()               {}
func (*ExternalReceipt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExternalReceipt) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ExternalReceipt) GetAccountID() []byte {
	if m != nil {
		return m.AccountID
	}
	return nil
}

func (m *ExternalReceipt) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *ExternalReceipt) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func init() {
	proto.RegisterType((*ExternalTx)(nil), "types.ExternalTx")
	proto.RegisterType((*ExternalReceipt)(nil), "types.ExternalReceipt")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x54, 0xb8, 0xb8, 0x5c,
	0x2b, 0x4a, 0x52, 0x8b, 0xf2, 0x12, 0x73, 0x42, 0x2a, 0x84, 0xc4, 0xb8, 0xd8, 0x3c, 0x32, 0x5d,
	0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0xa5, 0x6a, 0x2e, 0x7e,
	0x98, 0xaa, 0xa0, 0xd4, 0xe4, 0xd4, 0xcc, 0x82, 0x12, 0x21, 0x05, 0x2e, 0x6e, 0xa7, 0x9c, 0xfc,
	0xe4, 0x6c, 0x8f, 0xd4, 0xcc, 0xf4, 0x8c, 0x12, 0xb0, 0x7a, 0xe6, 0x20, 0x64, 0x21, 0x21, 0x19,
	0x2e, 0x4e, 0xc7, 0xe4, 0xe4, 0xfc, 0xd2, 0xbc, 0x12, 0x4f, 0x17, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0x9e, 0x20, 0x84, 0x00, 0xc8, 0xaa, 0x90, 0x0a, 0x8f, 0xc4, 0xe2, 0x0c, 0x09, 0x66, 0xb0, 0x14,
	0x94, 0x27, 0x24, 0xc0, 0xc5, 0xec, 0x93, 0x9f, 0x2e, 0xc1, 0x02, 0xb6, 0x1f, 0xc4, 0x4c, 0x62,
	0x03, 0x3b, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xea, 0x29, 0x5d, 0x82, 0xbf, 0x00, 0x00,
	0x00,
}
