// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_None                MsgType = 0
	MsgType_Tx                  MsgType = 1
	MsgType_BlockRequeste       MsgType = 4
	MsgType_BlockResponse       MsgType = 5
	MsgType_StatusRequest       MsgType = 6
	MsgType_StatusResponse      MsgType = 7
	MsgType_BlockHeaderRequest  MsgType = 8
	MsgType_BlockHeaderResponse MsgType = 9
	MsgType_NewRoundStep        MsgType = 10
	MsgType_CommitStep          MsgType = 11
	MsgType_Proposal            MsgType = 12
	MsgType_ProposalPOL         MsgType = 13
	MsgType_BlockPart           MsgType = 3
	MsgType_Vote                MsgType = 15
	MsgType_HasVote             MsgType = 16
	MsgType_VoteSetMaj23        MsgType = 17
	MsgType_VoteSetBits         MsgType = 18
	MsgType_PexRequest          MsgType = 19
	MsgType_PexAddrs            MsgType = 20
)

var MsgType_name = map[int32]string{
	0:  "None",
	1:  "Tx",
	4:  "BlockRequeste",
	5:  "BlockResponse",
	6:  "StatusRequest",
	7:  "StatusResponse",
	8:  "BlockHeaderRequest",
	9:  "BlockHeaderResponse",
	10: "NewRoundStep",
	11: "CommitStep",
	12: "Proposal",
	13: "ProposalPOL",
	3:  "BlockPart",
	15: "Vote",
	16: "HasVote",
	17: "VoteSetMaj23",
	18: "VoteSetBits",
	19: "PexRequest",
	20: "PexAddrs",
}
var MsgType_value = map[string]int32{
	"None":                0,
	"Tx":                  1,
	"BlockRequeste":       4,
	"BlockResponse":       5,
	"StatusRequest":       6,
	"StatusResponse":      7,
	"BlockHeaderRequest":  8,
	"BlockHeaderResponse": 9,
	"NewRoundStep":        10,
	"CommitStep":          11,
	"Proposal":            12,
	"ProposalPOL":         13,
	"BlockPart":           3,
	"Vote":                15,
	"HasVote":             16,
	"VoteSetMaj23":        17,
	"VoteSetBits":         18,
	"PexRequest":          19,
	"PexAddrs":            20,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_e707ccbba12de54f, []int{0}
}

type MsgResponseType int32

const (
	MsgResponseType_Unkown        MsgResponseType = 0
	MsgResponseType_DataExists    MsgResponseType = 1
	MsgResponseType_DataNotexists MsgResponseType = 2
)

var MsgResponseType_name = map[int32]string{
	0: "Unkown",
	1: "DataExists",
	2: "DataNotexists",
}
var MsgResponseType_value = map[string]int32{
	"Unkown":        0,
	"DataExists":    1,
	"DataNotexists": 2,
}

func (x MsgResponseType) String() string {
	return proto.EnumName(MsgResponseType_name, int32(x))
}
func (MsgResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_e707ccbba12de54f, []int{1}
}

type CheckMessage struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=Type,enum=p2p.MsgType" json:"Type,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMessage) Reset()         { *m = CheckMessage{} }
func (m *CheckMessage) String() string { return proto.CompactTextString(m) }
func (*CheckMessage) ProtoMessage()    {}
func (*CheckMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e707ccbba12de54f, []int{0}
}
func (m *CheckMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMessage.Unmarshal(m, b)
}
func (m *CheckMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMessage.Marshal(b, m, deterministic)
}
func (dst *CheckMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMessage.Merge(dst, src)
}
func (m *CheckMessage) XXX_Size() int {
	return xxx_messageInfo_CheckMessage.Size(m)
}
func (m *CheckMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMessage proto.InternalMessageInfo

func (m *CheckMessage) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_None
}

func (m *CheckMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BlockPartMessage struct {
	MsgId                string          `protobuf:"bytes,1,opt,name=MsgId" json:"MsgId,omitempty"`
	Response             MsgResponseType `protobuf:"varint,2,opt,name=Response,enum=p2p.MsgResponseType" json:"Response,omitempty"`
	Height               int64           `protobuf:"varint,3,opt,name=Height" json:"Height,omitempty"`
	Round                int64           `protobuf:"varint,4,opt,name=Round" json:"Round,omitempty"`
	Index                int32           `protobuf:"varint,5,opt,name=Index" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlockPartMessage) Reset()         { *m = BlockPartMessage{} }
func (m *BlockPartMessage) String() string { return proto.CompactTextString(m) }
func (*BlockPartMessage) ProtoMessage()    {}
func (*BlockPartMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e707ccbba12de54f, []int{1}
}
func (m *BlockPartMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockPartMessage.Unmarshal(m, b)
}
func (m *BlockPartMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockPartMessage.Marshal(b, m, deterministic)
}
func (dst *BlockPartMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPartMessage.Merge(dst, src)
}
func (m *BlockPartMessage) XXX_Size() int {
	return xxx_messageInfo_BlockPartMessage.Size(m)
}
func (m *BlockPartMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPartMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPartMessage proto.InternalMessageInfo

func (m *BlockPartMessage) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *BlockPartMessage) GetResponse() MsgResponseType {
	if m != nil {
		return m.Response
	}
	return MsgResponseType_Unkown
}

func (m *BlockPartMessage) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockPartMessage) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *BlockPartMessage) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckMessage)(nil), "p2p.CheckMessage")
	proto.RegisterType((*BlockPartMessage)(nil), "p2p.BlockPartMessage")
	proto.RegisterEnum("p2p.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("p2p.MsgResponseType", MsgResponseType_name, MsgResponseType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_e707ccbba12de54f) }

var fileDescriptor_message_e707ccbba12de54f = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xdf, 0x6e, 0xda, 0x4c,
	0x10, 0xc5, 0x63, 0x6c, 0x0c, 0x0c, 0x06, 0x26, 0x13, 0x94, 0xcf, 0x97, 0x56, 0xae, 0x50, 0x2e,
	0xd0, 0x27, 0xf2, 0x02, 0x6d, 0x92, 0x4a, 0x44, 0x2a, 0x14, 0x2d, 0x69, 0xef, 0xb7, 0xf1, 0x88,
	0x50, 0x82, 0x77, 0xeb, 0x5d, 0x14, 0xf7, 0x65, 0xfa, 0x2e, 0x7d, 0xb3, 0x6a, 0xd7, 0x76, 0xd4,
	0xf6, 0x6e, 0xcf, 0x6f, 0x67, 0xe6, 0x9c, 0xfd, 0x03, 0xa3, 0x23, 0x1b, 0x23, 0x77, 0x3c, 0xd7,
	0xa5, 0xb2, 0x8a, 0x42, 0xbd, 0xd0, 0x57, 0xf7, 0x90, 0xdc, 0x3d, 0xf3, 0xd3, 0x61, 0x55, 0x6f,
	0x51, 0x06, 0xd1, 0xe3, 0x0f, 0xcd, 0x69, 0x90, 0x05, 0xb3, 0xf1, 0x22, 0x99, 0xeb, 0x85, 0x9e,
	0xaf, 0xcc, 0xce, 0x31, 0xe1, 0x77, 0x88, 0x20, 0xba, 0x97, 0x56, 0xa6, 0x51, 0x16, 0xcc, 0x12,
	0xe1, 0xd7, 0x57, 0x3f, 0x03, 0xc0, 0xdb, 0x17, 0xf5, 0x74, 0xd8, 0xc8, 0xd2, 0xb6, 0xa3, 0xa6,
	0xd0, 0x5d, 0x99, 0xdd, 0x43, 0xee, 0x67, 0x0d, 0x44, 0x2d, 0xe8, 0x7f, 0xe8, 0x0b, 0x36, 0x5a,
	0x15, 0x86, 0xd3, 0x8e, 0x37, 0x99, 0xb6, 0x26, 0x2d, 0xf7, 0x66, 0x6f, 0x55, 0x74, 0x09, 0xf1,
	0x92, 0xf7, 0xbb, 0x67, 0x9b, 0x86, 0x59, 0x30, 0x0b, 0x45, 0xa3, 0xdc, 0x7c, 0xa1, 0x4e, 0x45,
	0xee, 0x93, 0x84, 0xa2, 0x16, 0x8e, 0x3e, 0x14, 0x39, 0x57, 0x69, 0x37, 0x0b, 0x66, 0x5d, 0x51,
	0x8b, 0xeb, 0x5f, 0x1d, 0xe8, 0x35, 0xc7, 0xa0, 0x3e, 0x44, 0x6b, 0x55, 0x30, 0x9e, 0x51, 0x0c,
	0x9d, 0xc7, 0x0a, 0x03, 0x3a, 0x87, 0x91, 0x4f, 0x2f, 0xf8, 0xfb, 0x89, 0x8d, 0x65, 0x8c, 0xfe,
	0x40, 0x75, 0x0a, 0xec, 0x3a, 0xb4, 0xb5, 0xd2, 0x9e, 0x4c, 0x53, 0x86, 0x31, 0x11, 0x8c, 0x5b,
	0xd4, 0x94, 0xf5, 0xe8, 0x12, 0xc8, 0x77, 0x2e, 0x59, 0xe6, 0x5c, 0xb6, 0xb5, 0x7d, 0xfa, 0x0f,
	0x2e, 0xfe, 0xe2, 0x4d, 0xc3, 0x80, 0x10, 0x92, 0x35, 0xbf, 0xfa, 0xf4, 0x5b, 0xcb, 0x1a, 0x81,
	0xc6, 0x00, 0x77, 0xea, 0x78, 0xdc, 0x5b, 0xaf, 0x87, 0x94, 0x40, 0x7f, 0x53, 0x2a, 0xad, 0x8c,
	0x7c, 0xc1, 0x84, 0x26, 0x30, 0x6c, 0xd5, 0xe6, 0xd3, 0x47, 0x1c, 0xd1, 0x08, 0x06, 0x6f, 0x97,
	0x8f, 0xa1, 0x3b, 0xdf, 0x17, 0x65, 0x19, 0x27, 0x34, 0x84, 0xde, 0x52, 0x1a, 0x2f, 0xd0, 0xd9,
	0xb8, 0xd5, 0x96, 0xed, 0x4a, 0x7e, 0x5b, 0xdc, 0xe0, 0xb9, 0x1b, 0xd4, 0x90, 0xdb, 0xbd, 0x35,
	0x48, 0xce, 0x77, 0xc3, 0x55, 0x1b, 0xf9, 0xc2, 0xfb, 0x72, 0xf5, 0x3e, 0xcf, 0x4b, 0x83, 0xd3,
	0xeb, 0x77, 0x30, 0xf9, 0xe7, 0x91, 0x08, 0x20, 0xfe, 0x5c, 0x1c, 0xd4, 0x6b, 0x81, 0x67, 0xae,
	0xd9, 0xfd, 0x85, 0x0f, 0xd5, 0xde, 0x58, 0x53, 0x5f, 0xaa, 0xd3, 0x6b, 0x65, 0xb9, 0x46, 0x9d,
	0xaf, 0xb1, 0xff, 0x78, 0x37, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x33, 0x10, 0x80, 0x89,
	0x02, 0x00, 0x00,
}
